# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('name', 'parent')]),
        ),
    ]
